version: "3.7"
services:
  api:
    build:
      context: .
    image: explorer:api
    container_name: explorer-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    depends_on:
      - db
  db:
    image: postgres:10
    restart: always
    container_name: explorer-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DATABASE}
